version: '3'

services:
  p:
    build: ./proxy
    ports:
      - '9090:9090'
      - '9901:9901'

  s:
    image: node:16
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: 'bash -c "npm i && node echo_server.js"'
    working_dir: /app/server
